name: CVector Python Test
description: Setup Poetry and run ruff, mypy, and pytest for Python projects

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.14"
  poetry-version:
    description: Poetry version to install
    required: false
    default: "2.2.1"
  src-dirs:
    description: Source directories for linting (space-separated)
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      id: setup
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.local
        key: poetry-${{ inputs.poetry-version }}

    - name: Install Poetry
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-path: ~/.venv

    - name: Load cached venv
      id: venv
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.venv
        key: venv-${{ runner.os }}-${{ steps.setup.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ steps.setup.outputs.python-version }}-

    - name: Sync dependencies
      if: steps.venv.outputs.cache-hit != 'true'
      shell: bash
      run: poetry sync --no-interaction --no-root

    - name: Install project
      shell: bash
      run: poetry install --no-interaction --only-root

    - name: Run ruff check
      shell: bash
      run: poetry run ruff check ${{ inputs.src-dirs }}

    - name: Run ruff format check
      shell: bash
      run: poetry run ruff format --check ${{ inputs.src-dirs }}

    - name: Run mypy
      shell: bash
      run: poetry run mypy ${{ inputs.src-dirs }}

    - name: Run pytest
      shell: bash
      run: poetry run pytest

branding:
  icon: check-circle
  color: orange
